"""create teams and team model access tables

Revision ID: adcf65b3c993
Revises:
Create Date: 2026-08-27 22:00:14.595404

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adcf65b3c993"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column("monthly_budget_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("priority_tier", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "team_model_access",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("logical_tier", sa.String(), nullable=False),
        sa.Column("primary_provider", sa.String(), nullable=False),
        sa.Column("primary_model", sa.String(), nullable=False),
        sa.Column("fallback_provider", sa.String(), nullable=True),
        sa.Column("fallback_model", sa.String(), nullable=True),
        sa.Column("rate_limit_rpm", sa.Integer(), nullable=False),
        sa.Column("rate_limit_tpm", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_model_access")
    op.drop_table("teams")
    # ### end Alembic commands ###
